name: stat

channels:
- conda-forge

dependencies:
- jupyter-server-proxy==4.5.0
- mystmd==1.10.1
- shiny==1.4.0
- pip:
  # Measure popularity of different packages in our hubs
  # https://discourse.jupyter.org/t/request-for-implementation-instrument-libraries-actively-used-by-users-on-a-jupyterhub/7994?u=yuvipanda
  - git+https://github.com/shaneknapp/python-popularity-contest.git@add-error-handling
  - jupyterlab-quarto==0.3.5
  - jupyter-positron-server==0.0.5
